[package]
name = "smallweb-adapter"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
tempfile = "3.10.1"

[[bin]]
name = "not-deno"
path = "src/main.rs"
